title: BSWG
description: Bridge Standards Working Group
baseurl: /
theme: jekyll-theme-minimal
markdown: kramdown
google_analytics: G-5CDYQRW253

subgroups: ['apis','conventions','data-policy','deals','form-grading','ids','points','results','system-notes','text-format']
areas: ['frameworks', 'eventdata','agreementsdata','playerdata']
frameworks: ['apis','text-format']
eventdata: ['deals','results']
agreementsdata: ['conventions','system-notes']
playerdata: ['data-policy','form-grading','ids','points']